create table if not exists public.valuation_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  paket text,
  rolle text,
  plz text,
  checkout_mode text not null,
  checkout_status text not null,
  market_value numeric,
  ai_summary text,
  form_data jsonb not null,
  result_data jsonb not null
);

alter table public.valuation_requests add column if not exists object_address text;
alter table public.valuation_requests add column if not exists city text;
alter table public.valuation_requests add column if not exists state text;
alter table public.valuation_requests add column if not exists property_category text;
alter table public.valuation_requests add column if not exists property_subtype text;
alter table public.valuation_requests add column if not exists living_area numeric;
alter table public.valuation_requests add column if not exists lot_area_share numeric;
alter table public.valuation_requests add column if not exists land_value_rate numeric;
alter table public.valuation_requests add column if not exists valuation_method text;
alter table public.valuation_requests add column if not exists report_version text;
alter table public.valuation_requests add column if not exists metadata jsonb not null default '{}'::jsonb;

create index if not exists valuation_requests_created_at_idx on public.valuation_requests (created_at desc);
create index if not exists valuation_requests_plz_idx on public.valuation_requests (plz);

alter table public.valuation_requests enable row level security;

drop policy if exists "Allow anon inserts for valuation requests" on public.valuation_requests;
create policy "Allow anon inserts for valuation requests"
on public.valuation_requests
for insert
to anon
with check (true);

drop policy if exists "Allow anon select valuation requests" on public.valuation_requests;
create policy "Allow anon select valuation requests"
on public.valuation_requests
for select
to anon
using (true);
